version: "3"

tasks:
  update:
    cmds:
      - nix flake update
      - task: nixos-rebuild
        vars:
          command: build
          host: adama
      - cachix push esselius ./result

  darwin:build:
    requires:
      vars:
        - host
    cmd: nix build .#darwinConfigurations.{{.host}}.config.system.build.toplevel --no-link -Lv

  darwin:switch:
    cmd: darwin-rebuild switch --flake . {{.CLI_ARGS}}

  home:build:
    requires:
      vars:
        - user
        - host
    cmd: nix build .#homeConfigurations.{{.user}}@{{.host}}.config.home.activationPackage  --no-link -Lv

  home:switch:
    cmd: home-manager switch --flake .

  nixos-rebuild:
    requires:
      vars:
        - command
        - host
    cmd: nixos-rebuild {{.command}} --flake .#{{.host}} {{.args}}

  nixos:build:
    requires:
      vars:
        - host
    cmd: nix build .#nixosConfigurations.{{.host}}.config.system.build.toplevel --no-link -Lv {{.CLI_ARGS}}

  nixos:switch:
    requires:
      vars:
        - host
    cmd:
      task: nixos-rebuild
      vars:
        command: switch
        args: --fast --use-remote-sudo --target-host {{.host}} {{.CLI_ARGS}}

  fmt:
    cmds:
      - statix fix
      - nixpkgs-fmt .
