name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  adama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28

      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-v2-adama-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-v2-adama-${{ runner.os }}-
          paths: |
            /nix/store
            ~/.cache/nix
            ~root/.cache/nix

      - run: nix --accept-flake-config --extra-experimental-features 'flakes nix-command' path-info --derivation .#nixosConfigurations.adama.config.system.build.toplevel --no-eval-cache

  cain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28

      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-v2-cain-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-v2-cain-${{ runner.os }}-
          paths: |
            /nix/store
            ~/.cache/nix
            ~root/.cache/nix

      - run: nix --accept-flake-config --extra-experimental-features 'flakes nix-command' path-info --derivation .#nixosConfigurations.cain.config.system.build.toplevel --no-eval-cache
