name: "Darwin Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  darwin-rebuild:
    strategy:
      matrix:
        host:
          - Fox
          - Petere-MBP
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          nix: true

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check darwin config
        run: nix run nix-darwin -- check --flake .#${{ matrix.host }}
