name: "Darwin Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check Fox darwin config
        run: nix run nix-darwin -- check --flake .#Fox

      - name: Check Petere-MBP darwin config
        run: nix run nix-darwin -- check --flake .#Petere-MBP
