name: "Darwin Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Build Fox darwin config
        run: nix run nix-darwin -- build --flake .#Fox
