name: "Darwin Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  darwin-rebuild:
    strategy:
      matrix:
        host:
          - Fox
          - Petere-MBP
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check darwin config
        run: nix run nix-darwin -- check --flake .#${{ matrix.host }}
