name: "Darwin Rebuild"
on:
  pull_request:
    paths-ignore:
      - nixos-*/**
  push:
    branches:
      - main
jobs:
  darwin-rebuild:
    strategy:
      matrix:
        host:
          - Fox
          - Petere-MBP
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Evaluate darwin config
        id: drv-check
        run: |
          echo -n result= >> $GITHUB_OUTPUT
          nix --accept-flake-config path-info --derivation .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel | base64 | tee /tmp/drv >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: cache-test
        with:
          path: /tmp/drv
          key: darwin-${{ hashFiles(format('{0}/{1}.{2}', 'darwin-configurations', matrix.host, 'nix')) }}-${{ steps.drv-check.outputs.result }}
          lookup-only: true

      - name: Build darwin config
        if: steps.cache-test.outputs.cache-hit != 'true'
        run: nix --accept-flake-config build .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel
