name: "Flake Checker"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: actions/cache@v4
        with:
          path: ~/.cache/nix
          key: nix-fc-${{ runner.os }}-${{ hashFiles('**/*.nix') }}

      - uses: DeterminateSystems/flake-checker-action@main
