name: "Flake Checker"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  flake-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v28

      - uses: DeterminateSystems/flake-checker-action@main

      - run: nix flake check
