name: "Home Manager"
on:
  pull_request:
    paths-ignore:
      - darwin-*/**
      - nixos-*/**
  push:
    branches:
      - main
jobs:
  home-manager:
    strategy:
      matrix:
        host:
          - Fox
          - Petere-MBP
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Check home-manager config
        run: nix path-info --derivation .#homeConfigurations."peteresselius@${{ matrix.host }}".activation-script
