name: "NixOS Tests"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - uses: rrbutani/use-nix-shell-action@v1

      - name: Monitoring Auth
        run: nix run .#nixosTests.monitoring-auth
