name: "NixOS Rebuild"
on:
  pull_request:
    paths-ignore:
      - darwin-*/**
      - home-*/**
      - nixos-tests/**
  push:
    branches:
      - main
jobs:
  nixos-rebuild:
    strategy:
      matrix:
        host:
          - adama
          - cain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_conf: extra-platforms = aarch64-linux

      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-nixos-${{ matrix.host }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-nixos-${{ matrix.host }}-
          save: github.ref == 'ref/head/main'

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Check nixos config
        run: nix path-info --derivation .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
