name: "NixOS Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nixos-rebuild:
    strategy:
      matrix:
        host:
          - adama
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3                                     # ⑴

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = aarch64-linux"

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Check nixos config
        run: nix run nixpkgs#nixos-rebuild -- build --flake .#${{ matrix.host }}
