name: "NixOS Tests"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nixos-tests:
    strategy:
      matrix:
        test:
          - monitoring-auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          nix: true
          gc-max-store-size: 1073741824

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Monitoring Auth
        run: nix run .#nixosTests.${{ matrix.test }}
