name: "NixOS Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - uses: rrbutani/use-nix-shell-action@v1

      - name: Monitoring Auth
        run: nix run .#nixosTests.monitoring-auth
