name: "NixOS Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check adama nixos config
        run: nix run nixpkgs#nixos-rebuild -- build --flake .#adama
