name: "NixOS Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nixos-rebuild:
    strategy:
      matrix:
        host:
          - adama
          - cain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - name: "Cache Nix store"
        uses: actions/cache@v3.0.8
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: nr-${{ runner.os }}-${{ hashFiles('**/*.nix') }}

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = aarch64-linux"

      - name: "Import Nix store cache"
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: "nix-store --import < /tmp/nixcache"

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Check nixos config
        run: nix run nixpkgs#nixos-rebuild -- build --flake .#${{ matrix.host }}

      - name: "Export Nix store cache"
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"
