name: "NixOS Rebuild"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nixos-rebuild:
    strategy:
      matrix:
        host:
          - adama
          - cain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: "extra-platforms = aarch64-linux"

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          nix: true

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Check nixos config
        run: nix run nixpkgs#nixos-rebuild -- build --flake .#${{ matrix.host }}
