name: "NixOS Tests"
on:
  pull_request:
    paths-ignore:
      - darwin-*/**
      - home-*/**
      - nixos-configurations/**
  push:
    branches:
      - main
jobs:
  nixos-tests:
    strategy:
      matrix:
        test:
          - monitoring-auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v28

      - uses: nix-community/cache-nix-action/restore@v5
        with:
          primary-key: nix-tests-${{ matrix.test }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-tests-${{ matrix.test }}-

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Check if test has changed
        id: drv-check
        run: |
          echo -n result= >> $GITHUB_OUTPUT
          nix path-info --derivation .#nixosTests.${{ matrix.test }} | base64 -w 0 | tee /tmp/drv >> $GITHUB_OUTPUT

      - uses: nix-community/cache-nix-action/save@v5
        if: github.ref == 'ref/head/main'
        with:
          primary-key: nix-tests-${{ matrix.test }}-${{ hashFiles('**/*.nix') }}

      - uses: actions/cache@v4
        id: cache-test
        with:
          path: /tmp/drv
          key: nixos-tests-${{ hashFiles(format('{0}/{1}.{2}', 'nixos-tests', matrix.test, 'nix')) }}-${{ steps.drv-check.outputs.result }}
          lookup-only: true

      - name: Run test
        if: steps.cache-test.outputs.cache-hit != 'true'
        run: nix run .#nixosTests.${{ matrix.test }}
