name: "NixOS Tests"
on:
  pull_request:
    paths-ignore:
      - darwin-*
  push:
    branches:
      - main
jobs:
  nixos-tests:
    strategy:
      matrix:
        test:
          - monitoring-auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v28

      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-tests-${{ matrix.test }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-tests-${{ matrix.test }}-
          save: github.ref == 'ref/head/main'

      - uses: cachix/cachix-action@v15
        with:
          name: esselius
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - name: Monitoring Auth
        run: nix run .#nixosTests.${{ matrix.test }}
